trigger:
  - master
  - refs/tags/*

pr:
  - master
  - master_based_androidx*
  
variables:
  BUILD_NUMBER: $(Build.BuildNumber)
  BUILD_COMMIT: $(Build.SourceVersion)
  DotNetCoreVersion: 3.1.x
  DotNet6Version: 6.0.100-alpha.1.21064.27
  DotNet6AndroidMsi:  https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/net6/4410065/master/dc1f7ba5f6fd5ba19de9377014b1536487838397/Microsoft.NET.Workload.Android.11.0.200.50.msi
  DotNet6AndroidPkg:  https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/net6/4410065/master/dc1f7ba5f6fd5ba19de9377014b1536487838397/Microsoft.NET.Workload.Android-11.0.200-ci.master.50.pkg
  XamarinAndroidVsix: https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/4410065/master/dc1f7ba5f6fd5ba19de9377014b1536487838397/signed/Xamarin.Android.Sdk-11.2.99.50.vsix
  XamarinAndroidPkg:  https://dl.internalx.com/vsts-devdiv/Xamarin.Android/public/4410065/master/dc1f7ba5f6fd5ba19de9377014b1536487838397/xamarin.android-11.2.99.50.pkg
  NugetSecurityAnalysisWarningLevel: warn
#   XAMARIN_ANDROID_PATH: <path to Xamarin.Android>

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
    - repository: components
      type: github
      name: xamarin/XamarinComponents
      endpoint: xamarin

jobs:
  - template: .ci/build.yml@components
    parameters:
      timeoutInMinutes: 240
      areaPath: 'DevDiv\Xamarin SDK\Android'
      dotnet: ''
      initSteps:
        - task: UseDotNet@2
          displayName: install .NET $(DotNetCoreVersion)
          inputs:
            version: $(DotNetCoreVersion)
            installationPath: /usr/local/share/dotnet/
          condition: eq(variables['System.JobName'], 'macos')
        - bash: >
            export DOTNET_ROOT=/usr/local/share/dotnet/ &&
            export PATH="$DOTNET_ROOT:~/.dotnet/tools:$PATH" &&
            curl -L https://dot.net/v1/dotnet-install.sh > dotnet-install.sh &&
            sh dotnet-install.sh --version $(DotNet6Version) --install-dir $DOTNET_ROOT --verbose &&
            dotnet --list-sdks &&
            echo "##vso[task.setvariable variable=PATH]$PATH"
          displayName: install .NET $(DotNet6Version)
          condition: eq(variables['System.JobName'], 'macos')
        - pwsh: |
            $ProgressPreference = 'SilentlyContinue'
            Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile dotnet-install.ps1
            & .\dotnet-install.ps1 -Version $(DotNet6Version) -InstallDir "$env:ProgramFiles\dotnet\" -Verbose
            & dotnet --list-sdks
          displayName: install .NET $(DotNet6Version)
          condition: eq(variables['System.JobName'], 'windows')
      preBuildSteps:
        - pwsh: |
            dotnet tool uninstall --global Cake.Tool
            dotnet tool install --global Cake.Tool
            dotnet tool install --global boots
          displayName: install .NET global tools
        - pwsh: |
            boots $(DotNet6AndroidPkg)
            boots $(XamarinAndroidPkg)
          condition: eq(variables['System.JobName'], 'macos')
          displayName: install Xamarin.Android
        - pwsh: |
            boots $(DotNet6AndroidMsi)
            boots $(XamarinAndroidVsix)
          condition: eq(variables['System.JobName'], 'windows')
          displayName: install Xamarin.Android
      tools:
        - 'xamarin.androidbinderator.tool': '0.4.3'
        - 'xamarin.androidx.migration.tool': '1.0.7.1'
  - ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
    - template: sign-artifacts/jobs/v2.yml@internal-templates
      parameters:
        timeoutInMinutes: 120
        dependsOn: [ 'build' ]
